#!/usr/bin/env python3
"""
export_tflite.py — INT8-quantize Begum model and OVERWRITE firmware/src/model_data.h.

- Loads training/artifacts/begum_fp32.keras (or .h5).
- Representative dataset: 500 random training samples (log-mel 49x40x1 float32).
- converter.target_spec.supported_ops = [TFLITE_BUILTINS_INT8]
  converter.inference_input_type / output_type = tf.int8 (fully quantized).
- Writes begum_int8.tflite; asserts size < 50KB else raises ValueError.
- Converts .tflite to C++ byte array (xxd -i equivalent) and OVERWRITES
  ../../firmware/src/model_data.h (relative to this script: ../firmware/src/model_data.h
  when run from training/, resolved robustly via __file__).

Usage:
    python export_tflite.py --artifacts ./artifacts --data_dir ./data
Requires Python 3.11+, tensorflow==2.15.0.
"""

import argparse
import random
from pathlib import Path

import numpy as np
import tensorflow as tf
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from train_model import wav_to_logmel  # reuse exact preprocessing

MAX_MODEL_BYTES = 50 * 1024  # 50KB strict


def collect_rep_files(data_dir: Path, n: int = 500):
    files = []
    for cls in ("positive", "negative", "noise"):
        files += list((data_dir / "train" / cls).glob("*.wav"))
    random.Random(7).shuffle(files)
    return files[:n]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--artifacts", default="./artifacts")
    ap.add_argument("--data_dir", default="./data")
    ap.add_argument("--model", default=None, help="override keras model path")
    args = ap.parse_args()

    artifacts = Path(args.artifacts)
    data_dir = Path(args.data_dir)
    model_path = Path(args.model) if args.model else None
    if model_path is None:
        for cand in (artifacts / "begum_fp32.keras", artifacts / "begum_fp32.h5",
                     artifacts / "stage2_best.keras"):
            if cand.exists():
                model_path = cand
                break
    if model_path is None or not model_path.exists():
        raise FileNotFoundError(f"No Keras model found in {artifacts}. Train first.")
    print(f"Loading {model_path} ...")
    model = tf.keras.models.load_model(str(model_path), compile=False)

    rep_files = collect_rep_files(data_dir, 500)
    if len(rep_files) < 50:
        raise FileNotFoundError(f"Need >=50 train wavs for calibration, found {len(rep_files)}")
    print(f"Calibration samples: {len(rep_files)}")
    rep_feats = []
    for f in rep_files:
        try:
            rep_feats.append(wav_to_logmel(str(f)))
        except Exception as e:
            print(f"  skip {f.name}: {e}")
    rep_feats = np.stack(rep_feats, axis=0).astype(np.float32)
    print("rep_feats:", rep_feats.shape, rep_feats.dtype)

    def rep_dataset():
        for i in range(len(rep_feats)):
            yield [rep_feats[i:i + 1]]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = rep_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    converter.allow_custom_ops = False

    print("Converting to INT8 ...")
    tflite_bytes = converter.convert()
    size = len(tflite_bytes)
    print(f"TFLite INT8 size: {size} bytes ({size/1024:.2f} KB)")
    if size > MAX_MODEL_BYTES:
        raise ValueError(f"Model too large: {size} bytes > {MAX_MODEL_BYTES} bytes (50KB). "
                         "Reduce filters/FC size and retrain.")

    out_tflite = artifacts / "begum_int8.tflite"
    out_tflite.write_bytes(tflite_bytes)
    print(f"Wrote {out_tflite}")

    # ---- xxd -i equivalent -> model_data.h (OVERWRITE) ----
    script_dir = Path(__file__).resolve().parent
    header_path = (script_dir / ".." / "firmware" / "src" / "model_data.h").resolve()
    header_path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("#ifndef BEGUM_MODEL_DATA_H")
    lines.append("#define BEGUM_MODEL_DATA_H")
    lines.append("")
    lines.append("// AUTO-GENERATED by training/export_tflite.py — DO NOT EDIT BY HAND.")
    lines.append(f"// INT8 TFLite model, {size} bytes ({size/1024:.2f} KB).")
    lines.append("// Overwrites the 20-byte dummy placeholder at first export.")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(f"const unsigned int begum_model_tflite_len = {size};")
    lines.append("const alignas(16) unsigned char begum_model_tflite[] = {")
    for off in range(0, size, 12):
        chunk = tflite_bytes[off:off + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ("," if off + 12 < size else ""))
    lines.append("};")
    lines.append("")
    lines.append("#endif // BEGUM_MODEL_DATA_H")
    lines.append("")
    header_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"OVERWROTE {header_path} with real {size}-byte INT8 model.")

    # sanity: interpreter smoke test
    it = tf.lite.Interpreter(model_content=tflite_bytes)
    it.allocate_tensors()
    inp = it.get_input_details()[0]
    scale, zp = inp["quantization"]
    q = np.clip(np.round(rep_feats[0:1] / scale + zp), -128, 127).astype(np.int8)
    it.set_tensor(inp["index"], q)
    it.invoke()
    out = it.get_tensor(it.get_output_details()[0]["index"])
    print("smoke invoke OK, raw int8 out:", out.reshape(-1)[:4])


if __name__ == "__main__":
    main()
